# -------------------------------------------------------
# Custom Pictures
# -------------------------------------------------------

avatar:
  enable: true
  url: /static/images/kamuyi.jpg

background:
  background_color: '#ffffff'

  # Custom Background Picture
  enable_picture: true
  url: /static/images/miku.jpg
  css_size: cover
  css_position: 50%


# -------------------------------------------------------
# Menu
# -------------------------------------------------------

menu:
  # Basic Menu
  Home: true
  Archives: true
  Categories: false
  Tags: false

  # Custom Menu
  # '/index' can be omitted
  # please add '/pages' as prefix
  # example:
  # [X]  About: /about/index       (need '/pages' as prefix)
  # [O]  About: /pages/about/index (preferred)
  # [O]  About: /pages/about
  # About: /pages/about/index

menu_icons:
  enable: true
  # icon name docs: http://fontawesome.io/icons/
  Home: fa-home
  Archives: fa-archive
  Categories: fa-bookmark
  Tags: fa-hashtag
  About: fa-smile-o

# -------------------------------------------------------
# Custom Blur
# -------------------------------------------------------
blur:
  background_color: '#ffffff'

  hide_overflow: true

  gaussian_radius:
    top_navigator: 30 # 30px+ preferred
    header: 5 # 5 ~ 50px preferred
    footer: 5 # 5 ~ 100px preferred

  font:
    color: '#ffffff' # only affect the font color in the blur area.


# -------------------------------------------------------
# Social
# -------------------------------------------------------

social:
  github: https://github.com/XiaoDangyh
  weibo: http://weibo.com/52hezhiyu

  # Email link, reference to https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#E-mail_links
  email: mailto:2670440804@qq.com


social_icons:
  enable: true
  # icon name docs: http://fontawesome.io/icons/
  github: fa-github-alt
  weibo: fa-weibo
  email: fa-envelope
  wechat: fa-weixin
  qq: fa-qq

# -------------------------------------------------------
# Page 404
# -------------------------------------------------------
page_404:
  # enable to use custom 404 page
  enable: false
  # filename of .md file path in your source dir
  # example:
  # after run command `hexo new page 404`
  # [X]  source_path: /404/index            (work dictionry is 'source')
  # [O]  source_path: 404/index.md
  # [O]  source_path: 404/index
  # [O]  source_path: 404                   ('/index' can be omitted)
  source_path: 404/index.md

# -------------------------------------------------------
# Comments System
# -------------------------------------------------------

# https://github.com/imsun/gitment#customize
gitment:
  enable: false
  github_id: # your github id
  repository_name: # your repository name

  # client_id & secret will generated after register an OAuth App
  # reference: https://github.com/settings/applications/new
  client_id:
  client_secret:
  per_page: 8 # comments per page
  max_comment_height: 250 # default 250px

# -------------------------------------------------------
# Google Analytics
# -------------------------------------------------------

google_analytics:
  enable: false
  track_id: UA-XXXXXX-X # replace to your track_id. It starts with 'UA-'.


# -------------------------------------------------------
# Powered by
# -------------------------------------------------------
powered_by: Hexo Theme Lite
